const NOTIFICATION_TYPES = {
  // Recruitment & Applications
  APPLICATION_RECEIVED: "APPLICATION_RECEIVED",
  APPLICATION_STATUS_CHANGED: "APPLICATION_STATUS_CHANGED",

  // Interviews
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_RESCHEDULED: "INTERVIEW_RESCHEDULED",
  INTERVIEW_CANCELLED: "INTERVIEW_CANCELLED",

  // Hiring & Conversion
  CANDIDATE_HIRED: "CANDIDATE_HIRED",

  // Leave Management
  LEAVE_REQUESTED: "LEAVE_REQUESTED",
  LEAVE_APPROVED: "LEAVE_APPROVED",
  LEAVE_REJECTED: "LEAVE_REJECTED",
  LEAVE_CANCELLED: "LEAVE_CANCELLED",
};

module.exports = NOTIFICATION_TYPES;
